-- Drop table if exists
DROP TABLE IF EXISTS customer;

-- Create table
CREATE TABLE customer (
                          id SERIAL PRIMARY KEY,
                          cgid VARCHAR(20),
                          full_name VARCHAR(100) NOT NULL,
                          email VARCHAR(100) NOT NULL,
                          phone VARCHAR(20) NOT NULL,
                          gender VARCHAR(10),
                          customer_type VARCHAR(20),
                          city VARCHAR(50),
                          state VARCHAR(50),
                          country VARCHAR(50),
                          pincode VARCHAR(10),

    -- New profile fields
                          age_group VARCHAR(50),                  -- e.g., "25–35"
                          income_bracket VARCHAR(100),            -- e.g., "5–10 LPA"
                          profession VARCHAR(100),                -- e.g., "IT", "Healthcare"
                          spending_patterns VARCHAR(255),         -- e.g., "Travel, Dining"
                          loan_history VARCHAR(255),              -- e.g., "Existing home loan"
                          investment_preferences VARCHAR(255),    -- e.g., "Mutual Funds, FDs"
                          digital_engagement_level VARCHAR(100),  -- e.g., "Mobile App User"
                          preferred_channel VARCHAR(50)        -- e.g., "Email", "WhatsApp"


);


DROP TABLE IF EXISTS marketing_requests;
CREATE TABLE marketing_requests (
                                    id SERIAL PRIMARY KEY,
                                    customer_id VARCHAR(50) NOT NULL,
                                    customer_type VARCHAR(50),
                                    product_type TEXT,
                                    email TEXT,
                                    status VARCHAR(20) DEFAULT 'Pending',
                                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- V3__insert_dummy_customer.sql


INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-001', 'Rajiv Sharma', 'vinayak270603@gmail.com', '9876543210', 'Male', 'Premium', 'Delhi', 'Delhi', 'India', '110001', '25-35', '10-15 LPA', 'IT Professional', 'Travel, Shopping', 'Closed personal loan', 'Mutual Funds, Stocks', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-002', 'Neha Gupta', 'neha.gupta@example.com', '9123456789', 'Female', 'Standard', 'Mumbai', 'Maharashtra', 'India', '400001', '35-45', '5-10 LPA', 'Healthcare Worker', 'Dining, Shopping', 'Existing home loan', 'FDs, Insurance', 'Net Banking User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-003', 'Amit Verma', 'amit.verma@example.com', '9988776655', 'Male', 'Gold', 'Bengaluru', 'Karnataka', 'India', '560001', '45-55', '15-20 LPA', 'Government Employee', 'Minimal Spending', 'No loans', 'Stocks, Mutual Funds', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-100', 'Person 1', 'person1@example.com', '9251666453', 'Male', 'Standard', 'Chennai', 'Telangana', 'India', '815110', '45-55', '10-15 LPA', 'IT Professional', 'Luxury Goods', 'Existing car loan', 'FDs, Insurance', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-101', 'Person 2', 'person2@example.com', '9970615455', 'Other', 'Silver', 'Bengaluru', 'Telangana', 'India', '455585', '55-65', '>20 LPA', 'Business Owner', 'Minimal Spending', 'Existing home loan', 'Gold, Real Estate', 'Mobile App User', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-102', 'Person 3', 'person3@example.com', '9368289465', 'Female', 'Premium', 'Kolkata', 'West Bengal', 'India', '643220', '45-55', '>20 LPA', 'Engineer', 'Luxury Goods', 'Closed personal loan', 'FDs, Insurance', 'Net Banking User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-103', 'Person 4', 'person4@example.com', '9828448652', 'Other', 'Gold', 'Delhi', 'Delhi', 'India', '974284', '55-65', '5-10 LPA', 'IT Professional', 'Education, Healthcare', 'Existing car loan', 'FDs, Insurance', 'Net Banking User', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-104', 'Person 5', 'person5@example.com', '9200412818', 'Male', 'Premium', 'Chennai', 'Tamil Nadu', 'India', '113011', '45-55', '15-20 LPA', 'IT Professional', 'Dining, Shopping', 'Existing home loan', 'Stocks, Mutual Funds', 'Net Banking User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-105', 'Person 6', 'person6@example.com', '9553842311', 'Female', 'Premium', 'Chennai', 'Delhi', 'India', '992521', '25-35', '>20 LPA', 'Doctor', 'Luxury Goods', 'No loans', 'FDs, Insurance', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-106', 'Person 7', 'person7@example.com', '9218297010', 'Female', 'Premium', 'Hyderabad', 'Karnataka', 'India', '611778', '45-55', '5-10 LPA', 'Teacher', 'Dining, Shopping', 'Existing home loan', 'Stocks, Mutual Funds', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-107', 'Person 8', 'person8@example.com', '9681543198', 'Female', 'Gold', 'Chennai', 'Tamil Nadu', 'India', '558212', '25-35', '>20 LPA', 'Business Owner', 'Minimal Spending', 'Closed personal loan', 'Stocks, Mutual Funds', 'Mobile App User', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-108', 'Person 9', 'person9@example.com', '9789473538', 'Male', 'Standard', 'Hyderabad', 'Tamil Nadu', 'India', '744023', '35-45', '<5 LPA', 'Government Employee', 'Minimal Spending', 'No loans', 'Mutual Funds, Stocks', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-109', 'Person 10', 'person10@example.com', '9285976792', 'Male', 'Standard', 'Kolkata', 'Delhi', 'India', '565735', '55-65', '>20 LPA', 'Teacher', 'Minimal Spending', 'Existing car loan', 'Stocks, Mutual Funds', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-110', 'Person 11', 'person11@example.com', '9894887801', 'Male', 'Premium', 'Chennai', 'Telangana', 'India', '454096', '18-25', '<5 LPA', 'Government Employee', 'Travel, Shopping', 'No loans', 'Stocks, Mutual Funds', 'Net Banking User', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-111', 'Person 12', 'person12@example.com', '9714674372', 'Male', 'Standard', 'Bengaluru', 'Telangana', 'India', '134386', '35-45', '>20 LPA', 'Doctor', 'Dining, Shopping', 'Closed personal loan', 'FDs, Insurance', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-112', 'Person 13', 'person13@example.com', '9742384217', 'Male', 'Premium', 'Kolkata', 'Delhi', 'India', '487624', '25-35', '15-20 LPA', 'Engineer', 'Luxury Goods', 'Closed personal loan', 'Gold, Real Estate', 'Mobile App User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-113', 'Person 14', 'person14@example.com', '9802242790', 'Female', 'Standard', 'Delhi', 'Telangana', 'India', '808730', '35-45', '15-20 LPA', 'Government Employee', 'Dining, Shopping', 'Existing car loan', 'FDs, Insurance', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-114', 'Person 15', 'person15@example.com', '9807661559', 'Male', 'Silver', 'Delhi', 'Maharashtra', 'India', '243216', '25-35', '5-10 LPA', 'Government Employee', 'Luxury Goods', 'Existing home loan', 'FDs, Insurance', 'Net Banking User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-115', 'Person 16', 'person16@example.com', '9175275894', 'Male', 'Premium', 'Bengaluru', 'West Bengal', 'India', '955853', '25-35', '>20 LPA', 'Government Employee', 'Luxury Goods', 'Closed personal loan', 'FDs, Insurance', 'Both App & Net Banking', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-116', 'Person 17', 'person17@example.com', '9946317385', 'Female', 'Gold', 'Hyderabad', 'Delhi', 'India', '184940', '25-35', '<5 LPA', 'IT Professional', 'Dining, Shopping', 'No loans', 'Gold, Real Estate', 'Mobile App User', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-117', 'Person 18', 'person18@example.com', '9710026122', 'Male', 'Premium', 'Chennai', 'Telangana', 'India', '158277', '18-25', '10-15 LPA', 'Business Owner', 'Dining, Shopping', 'No loans', 'Gold, Real Estate', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-118', 'Person 19', 'person19@example.com', '9282233093', 'Other', 'Premium', 'Mumbai', 'Tamil Nadu', 'India', '883810', '55-65', '>20 LPA', 'Engineer', 'Education, Healthcare', 'Existing car loan', 'FDs, Insurance', 'Mobile App User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-119', 'Person 20', 'person20@example.com', '9979413666', 'Other', 'Premium', 'Hyderabad', 'West Bengal', 'India', '508790', '45-55', '>20 LPA', 'Business Owner', 'Education, Healthcare', 'Existing car loan', 'Stocks, Mutual Funds', 'Mobile App User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-120', 'Person 21', 'person21@example.com', '9127176048', 'Other', 'Premium', 'Delhi', 'Tamil Nadu', 'India', '540642', '25-35', '<5 LPA', 'Business Owner', 'Luxury Goods', 'Existing car loan', 'FDs, Insurance', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-121', 'Person 22', 'person22@example.com', '9575046801', 'Other', 'Gold', 'Delhi', 'Maharashtra', 'India', '587360', '18-25', '15-20 LPA', 'Doctor', 'Minimal Spending', 'Closed personal loan', 'Stocks, Mutual Funds', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-122', 'Person 23', 'person23@example.com', '9934483732', 'Female', 'Silver', 'Hyderabad', 'Karnataka', 'India', '179498', '18-25', '>20 LPA', 'Doctor', 'Luxury Goods', 'No loans', 'Stocks, Mutual Funds', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-123', 'Person 24', 'person24@example.com', '9368497595', 'Other', 'Standard', 'Mumbai', 'West Bengal', 'India', '485963', '55-65', '>20 LPA', 'Teacher', 'Travel, Shopping', 'Existing home loan', 'Stocks, Mutual Funds', 'Net Banking User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-124', 'Person 25', 'person25@example.com', '9242115985', 'Other', 'Standard', 'Delhi', 'Karnataka', 'India', '885054', '55-65', '15-20 LPA', 'Engineer', 'Travel, Shopping', 'Closed personal loan', 'Gold, Real Estate', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-125', 'Person 26', 'person26@example.com', '9907102466', 'Other', 'Silver', 'Kolkata', 'Tamil Nadu', 'India', '475172', '45-55', '10-15 LPA', 'Business Owner', 'Travel, Shopping', 'Existing home loan', 'Stocks, Mutual Funds', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-126', 'Person 27', 'person27@example.com', '9772905600', 'Female', 'Premium', 'Delhi', 'Delhi', 'India', '354269', '18-25', '10-15 LPA', 'Teacher', 'Dining, Shopping', 'No loans', 'Stocks, Mutual Funds', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-127', 'Person 28', 'person28@example.com', '9910957584', 'Other', 'Gold', 'Hyderabad', 'Tamil Nadu', 'India', '318011', '25-35', '5-10 LPA', 'IT Professional', 'Travel, Shopping', 'Existing home loan', 'Gold, Real Estate', 'Mobile App User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-128', 'Person 29', 'person29@example.com', '9100520730', 'Female', 'Gold', 'Mumbai', 'Karnataka', 'India', '407569', '55-65', '>20 LPA', 'Teacher', 'Luxury Goods', 'No loans', 'Gold, Real Estate', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-129', 'Person 30', 'person30@example.com', '9320955457', 'Other', 'Standard', 'Bengaluru', 'Karnataka', 'India', '854009', '35-45', '10-15 LPA', 'Business Owner', 'Minimal Spending', 'Closed personal loan', 'FDs, Insurance', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-130', 'Person 31', 'person31@example.com', '9961982156', 'Other', 'Silver', 'Mumbai', 'Karnataka', 'India', '572166', '35-45', '<5 LPA', 'Government Employee', 'Dining, Shopping', 'Closed personal loan', 'Stocks, Mutual Funds', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-131', 'Person 32', 'person32@example.com', '9419494261', 'Male', 'Silver', 'Bengaluru', 'Tamil Nadu', 'India', '238985', '45-55', '<5 LPA', 'Government Employee', 'Luxury Goods', 'Existing car loan', 'Mutual Funds, Stocks', 'Mobile App User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-132', 'Person 33', 'person33@example.com', '9549696840', 'Male', 'Premium', 'Bengaluru', 'Telangana', 'India', '345217', '45-55', '5-10 LPA', 'Engineer', 'Luxury Goods', 'Existing car loan', 'Gold, Real Estate', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-133', 'Person 34', 'person34@example.com', '9959378014', 'Other', 'Gold', 'Hyderabad', 'West Bengal', 'India', '733139', '45-55', '10-15 LPA', 'Government Employee', 'Luxury Goods', 'Existing home loan', 'Mutual Funds, Stocks', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-134', 'Person 35', 'person35@example.com', '9685030202', 'Other', 'Gold', 'Delhi', 'West Bengal', 'India', '667199', '45-55', '15-20 LPA', 'Engineer', 'Dining, Shopping', 'Closed personal loan', 'Gold, Real Estate', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-135', 'Person 36', 'person36@example.com', '9367210090', 'Female', 'Standard', 'Kolkata', 'West Bengal', 'India', '449512', '18-25', '10-15 LPA', 'Engineer', 'Minimal Spending', 'Existing car loan', 'Stocks, Mutual Funds', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-136', 'Person 37', 'person37@example.com', '9737101266', 'Male', 'Standard', 'Delhi', 'West Bengal', 'India', '174246', '45-55', '10-15 LPA', 'Doctor', 'Education, Healthcare', 'Closed personal loan', 'Gold, Real Estate', 'Mobile App User', 'WhatsApp');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-137', 'Person 38', 'person38@example.com', '9553939209', 'Other', 'Silver', 'Mumbai', 'Delhi', 'India', '809364', '45-55', '>20 LPA', 'Business Owner', 'Minimal Spending', 'Closed personal loan', 'Gold, Real Estate', 'Both App & Net Banking', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-138', 'Person 39', 'person39@example.com', '9665198167', 'Other', 'Standard', 'Mumbai', 'Karnataka', 'India', '909109', '35-45', '<5 LPA', 'Doctor', 'Travel, Shopping', 'Existing car loan', 'Stocks, Mutual Funds', 'Net Banking User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-139', 'Person 40', 'person40@example.com', '9869805114', 'Female', 'Premium', 'Mumbai', 'Karnataka', 'India', '215135', '45-55', '10-15 LPA', 'Doctor', 'Luxury Goods', 'Existing home loan', 'Mutual Funds, Stocks', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-140', 'Person 41', 'person41@example.com', '9792749253', 'Other', 'Silver', 'Mumbai', 'Karnataka', 'India', '323370', '18-25', '15-20 LPA', 'Business Owner', 'Education, Healthcare', 'Existing home loan', 'Gold, Real Estate', 'Net Banking User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-141', 'Person 42', 'person42@example.com', '9166504832', 'Other', 'Gold', 'Delhi', 'Telangana', 'India', '349975', '55-65', '15-20 LPA', 'Doctor', 'Dining, Shopping', 'Existing car loan', 'FDs, Insurance', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-142', 'Person 43', 'person43@example.com', '9107972077', 'Other', 'Silver', 'Mumbai', 'Karnataka', 'India', '552763', '18-25', '15-20 LPA', 'IT Professional', 'Minimal Spending', 'Closed personal loan', 'FDs, Insurance', 'Mobile App User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-143', 'Person 44', 'person44@example.com', '9812543993', 'Male', 'Standard', 'Chennai', 'Telangana', 'India', '838698', '25-35', '10-15 LPA', 'Government Employee', 'Minimal Spending', 'Closed personal loan', 'Stocks, Mutual Funds', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-144', 'Person 45', 'person45@example.com', '9386589730', 'Male', 'Gold', 'Chennai', 'West Bengal', 'India', '541803', '55-65', '<5 LPA', 'Engineer', 'Minimal Spending', 'Existing car loan', 'FDs, Insurance', 'Net Banking User', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-145', 'Person 46', 'person46@example.com', '9677549997', 'Male', 'Gold', 'Hyderabad', 'Delhi', 'India', '368517', '25-35', '5-10 LPA', 'Business Owner', 'Dining, Shopping', 'Existing car loan', 'Mutual Funds, Stocks', 'Mobile App User', 'Phone Call');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-146', 'Person 47', 'person47@example.com', '9393056965', 'Male', 'Silver', 'Hyderabad', 'Karnataka', 'India', '407462', '35-45', '5-10 LPA', 'Teacher', 'Education, Healthcare', 'Existing car loan', 'FDs, Insurance', 'Mobile App User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-147', 'Person 48', 'person48@example.com', '9336878766', 'Other', 'Silver', 'Mumbai', 'Maharashtra', 'India', '778111', '55-65', '<5 LPA', 'Government Employee', 'Education, Healthcare', 'Closed personal loan', 'Mutual Funds, Stocks', 'Both App & Net Banking', 'Email');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-148', 'Person 49', 'person49@example.com', '9320905497', 'Female', 'Gold', 'Chennai', 'Telangana', 'India', '280071', '25-35', '10-15 LPA', 'IT Professional', 'Travel, Shopping', 'Existing car loan', 'FDs, Insurance', 'Mobile App User', 'SMS');
INSERT INTO customer (cgid, full_name, email, phone, gender, customer_type, city, state, country, pincode, age_group, income_bracket, profession, spending_patterns, loan_history, investment_preferences, digital_engagement_level, preferred_channel) VALUES ('CGID-149', 'Person 50', 'person50@example.com', '9800724752', 'Other', 'Standard', 'Chennai', 'Telangana', 'India', '209370', '45-55', '>20 LPA', 'IT Professional', 'Education, Healthcare', 'Existing car loan', 'Mutual Funds, Stocks', 'Net Banking User', 'WhatsApp');